---
name: ansible_cointainer_ci

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * 6'

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: hferreira/ansible-docker

jobs:
  build-amd64:
    name: Build amd64 image
    runs-on: ubuntu-latest
    outputs:
      docker-image-amd: ${{ env.IMAGE_NAME }}:amd64
      ghcr-image-amd: ghcr.io/${{ github.repository }}:amd64
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (linux/amd64)
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:amd64
            ghcr.io/${{ github.repository }}:amd64

  build-arm64:
    name: Build arm64 image
    runs-on: ubuntu-24.04-arm
    outputs:
      docker-image-arm: ${{ env.IMAGE_NAME }}:arm64
      ghcr-image-arm: ghcr.io/${{ github.repository }}:arm64
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (linux/arm64)
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:arm64
            ghcr.io/${{ github.repository }}:arm64

  create-manifest:
    name: Create and push multi-arch manifests
    needs: [build-amd64, build-arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx (for imagetools)
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push multi-arch manifests (DockerHub + GHCR)
        run: |
          # docker buildx imagetools create will assemble a manifest list from existing images
          docker buildx imagetools create --tag "${{ env.IMAGE_NAME }}:latest" \
            "${{ env.IMAGE_NAME }}:amd64" \
            "${{ env.IMAGE_NAME }}:arm64"

          docker buildx imagetools create --tag "ghcr.io/${{ github.repository }}:latest" \
            "ghcr.io/${{ github.repository }}:amd64" \
            "ghcr.io/${{ github.repository }}:arm64"
